### ISSUE TITLE
Home Page Canonical Url issue

### ISSUE THREAD

**Issue by xeontcs** [nenes25/magento2-cms#1]
Hi,

Thank you for this Extension.

It works with M2.3.

The only issue is it is adding /home to the home page Canonical Url.

`<link rel="canonical" href="https://domain.tld/home"/>`

**Comment by nenes25** [comment]
Hi @xeontcs ,

Thanks for the feedback :)
I'll check to disable this behavior

Regards,

**Comment by xeontcs** [comment]
@nenes25 Thank you!

Looking forward for the fix.

**Comment by nenes25** [comment]
Hi,
Could you confirm that it works well on your side ?
Regards,

**Comment by xeontcs** [comment]
Hi,

Yes, It works!

Thank you very much.

This is a very useful and light-weight extension does the Job.
