### ISSUE TITLE
Tag Release

### ISSUE THREAD

**Issue by sprankhub** [nenes25/magento2-cms#2]
Could you please [tag a new release](https://github.com/nenes25/magento2-cms/releases) here in GitHub, so that we can require a specific version via Composer?

Additionally, could we make this `1.0.0` and not `0.*`? The extension looks pretty solid :)

Thanks!

**Comment by nenes25** [comment]
Hello,

Thanks for your feedback.
The change have been done.

Please let me know if it solve your issue :)

Regards,

**Comment by sprankhub** [comment]
Thanks @nenes25!
